spring:
  application:
    name: api
  security:
    user:
      name: actuator
      password: actuatorpassword123!

server:
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers
  endpoint:
    health:
      show-details: when_authorized          # or 'when_authorized' if using Security
      probes:
        enabled: true              # exposes /actuator/health/liveness & /readiness
  metrics:
    tags:
      application: ${spring.application.name:api}